// Stub generated by Convex CLI — run `npx convex codegen` to regenerate
import type {
  DataModelFromSchemaDefinition,
  DocumentByName,
  GenericDataModel,
  GenericDatabaseReader,
  GenericDatabaseWriter,
  TableNamesInDataModel,
} from "convex/server";
import type { GenericId } from "convex/values";
import schema from "../schema.js";

type DataModel = DataModelFromSchemaDefinition<typeof schema>;

type GenericCtx = {
  db: GenericDatabaseReader<GenericDataModel>;
};

export declare const query: <Args extends any[], Output>(
  func: (ctx: GenericCtx, ...args: Args) => Output
) => any;

export declare const mutation: <Args extends any[], Output>(
  func: (ctx: GenericCtx & { db: GenericDatabaseWriter<GenericDataModel> }, ...args: Args) => Output
) => any;

export type Id<TableName extends TableNamesInDataModel<DataModel>> =
  GenericId<TableName>;

export type Document<TableName extends TableNamesInDataModel<DataModel>> =
  DocumentByName<DataModel, TableName>;
